### ISSUE TITLE
reverse words in a string

### ISSUE THREAD

**Issue by Lucifer39** [sayandas722/Hacktoberfest22-OOPS-java.code#24]

**Comment by gaurav-iitb** [comment]
please assign this to me

**Comment by gaurav-iitb** [comment]
this question is already merged is it still open . what should I do

**Comment by sayandas722** [comment]
> this question is already merged is it still open . what should I do

u can upload ur version ... i will merge

**Comment by gaurav-iitb** [comment]
I can't see any contribution.md file in your repo which iguess is mandatory in hacktoberfest.

**Comment by sayandas722** [comment]
u havent made a pull request.... make a pull request .. so that i can merge 

fork my repo 
add file 
upload it 
make a pull req
