### ISSUE TITLE
Try Catch Finally

### ISSUE THREAD

**Issue by sayandas722** [sayandas722/Hacktoberfest22-OOPS-java.code#35]

**Comment by Subhadas2000** [comment]
please assign this to me

**Comment by island-coder** [comment]
can I work on this? Thanks

**Comment by dmdbilal** [comment]
I want to work on this issue.

**Comment by NikhilCode12** [comment]
kindly assign this issue to me I have completed dsa you can see my leetcode profile here https://leetcode.com/Nikhilcode123/
i will write it efficiently and explain with graphical drawing as well, this can be my first contribution.
