### ISSUE TITLE
Exception Handling 

### ISSUE THREAD

**Issue by sayandas722** [sayandas722/Hacktoberfest22-OOPS-java.code#6]

**Comment by sarthak17jain** [comment]
Please assign me this issue.

**Comment by Subhadas2000** [comment]
Hi can you assign this to me?

**Comment by SoumyadeepMukherjee** [comment]
Kindly assign me this issue

**Comment by Sandyy07** [comment]
I am good with Exceptional Handling in Java . Can you please assign me this issue
